app-id: io.github.kuingsmile.PicList
runtime: org.freedesktop.Platform
runtime-version: '26.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '26.08'
command: piclist
separate-locales: false
finish-args:
  - --share=ipc
  - --share=network
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --filesystem=xdg-download
  - --filesystem=xdg-pictures
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --system-talk-name=org.freedesktop.login1
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=com.canonical.AppMenu.Registrar
  - --talk-name=com.canonical.AppMenu.Registrar.*
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc

modules:
  - name: piclist
    buildsystem: simple
    build-commands:
      - bsdtar -xf piclist.deb
      - bsdtar -xf data.tar.xz
      - mv opt/PicList ${FLATPAK_DEST}/PicList
      - install -Dvm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/
      - install -Dvm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications/
      - install -Dvm644 ${FLATPAK_ID}.metainfo.xml ${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.metainfo.xml
      - install -Dvm755 piclist.sh /app/bin/piclist
    sources:
      - type: file
        dest-filename: piclist.deb
        only-arches:
          - x86_64
        url: https://github.com/Kuingsmile/PicList/releases/download/v3.5.0/PicList-3.5.0-amd64.deb
        sha256: 301cd66712065643ff5fca5b001b4c0c399dfd55a382f59168a047d5c51e64e6
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Kuingsmile/PicList/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name == "PicList-" + $version + "-amd64.deb")
            | .browser_download_url
      - type: script
        dest-filename: piclist.sh
        commands:
          - |
            if [ -n "${WAYLAND_DISPLAY:-}" ]; then
              args="--enable-wayland-ime --wayland-text-input-version=3"
            else
              args=""
            fi
          - exec zypak-wrapper /app/PicList/PicList $args "$@"
      - type: file
        path: io.github.kuingsmile.PicList.png
      - type: file
        path: io.github.kuingsmile.PicList.desktop
      - type: file
        path: io.github.kuingsmile.PicList.metainfo.xml
