name: Build and test

on:
  pull_request:
    branches:
      - stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

# Variables:
# - MANIFESTS_DIR: manifest 存储根目录
# - REPO_NAME: --repo=$REPO_NAME，需要上传的仓库元数据文件夹
# - BUILD_DIR: 构建目录
env:
  MANIFESTS_DIR: ${{ vars.MANIFESTS_DIR }}
  REPO_NAME: ${{ vars.REPO_NAME }}
  BUILD_DIR: ${{ vars.BUILD_DIR }}

jobs:
  metadata:
    runs-on: ubuntu-24.04
    outputs:
      apps: ${{ steps.matrix.outputs.apps }}
      has_changes: ${{ steps.matrix.outputs.has_changes }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Diff as json
        id: diff
        uses: GrantBirki/git-diff-action@v2.8.1
        with:
          base_branch: ${{ github.event.pull_request.base.sha }}
          file_output_only: true
          search_path: ${{ env.MANIFESTS_DIR }}
          json_diff_file_output: diff.json

      - name: Print json diff
        run: cat ${{ steps.diff.outputs.json-diff-path }}

      - name: Generate Matrix
        id: matrix
        run: |
          apps=""
          DIFF_FILE=${{ steps.diff.outputs.json-diff-path }}
          for file in $(jq -r '.files[].path' "$DIFF_FILE"); do
            if [[ "$file" =~ ^manifests/([^/]+)/ ]]; then
              app_id="${BASH_REMATCH[1]}"
              if [[ ! " $apps " =~ " $app_id " ]]; then
                apps="$apps $app_id"
              fi
            fi
          done
          apps=$(echo "$apps" | xargs)

          if [ -z "$apps" ]; then
            echo "apps=" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "apps: $apps"
            echo "apps=$apps" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-24.04
    needs: metadata
    if: needs.metadata.outputs.has_changes == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup flatpak
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          sudo apt-get update -y
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build packages
        run: |
          for app in ${{ needs.metadata.outputs.apps }}; do
            manifest_file="${{ env.MANIFESTS_DIR }}/${app}/${app}.yaml"
            flatpak-builder \
              --user \
              --force-clean \
              --disable-updates \
              --disable-rofiles-fuse \
              --default-branch=beta \
              --install-deps-from=flathub \
              --repo=${{ env.REPO_NAME }} \
              ${{ env.BUILD_DIR }} \
              "$manifest_file"
          done
